### ISSUE TITLE
Redmine by Project won't post to RocketChat webhook

### ISSUE THREAD

**Issue by mnash04** [scantem/redmine_rocketchat#2]
Running Redmine 3.2 and RocketChat 0.55.1.
-Redmine integration successfully posts via webhook to RocketChat channel
-However, when using the projects/custom fields, nothing gets posted.

Thoughts?

**Comment by scantem** [comment]
I'm running Rocket.Chat 52 at the moment and will upgrade it later this week to test. I've just merged the latest changes from the Mattermost fork, could you please give that a try as it might have fixed your problems.

**Comment by mnash04** [comment]
Works like a charm.
Just need to use "Rocketchat URL" and "Rocketchat Channel" now.

**Comment by scantem** [comment]
Excellent, thanks for letting me know
